//! Compiles `payload.wat` → WebAssembly and injects bytes into `src/wasm_payload.rs`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let wat_path = manifest_dir.join("payload.wat");
    let out_path = manifest_dir.join("src").join("wasm_payload.rs");

    println!("cargo:rerun-if-changed=payload.wat");
    println!("cargo:rerun-if-changed=build.rs");

    if !wat_path.is_file() {
        panic!(
            "missing {} — add a WebAssembly text module at the project root",
            wat_path.display()
        );
    }

    let wat_source = fs::read_to_string(&wat_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", wat_path.display()));

    let wasm = wat::parse_str(&wat_source).unwrap_or_else(|e| {
        panic!("failed to compile {}: {e}", wat_path.display());
    });

    let rust = generate_rust(&wasm);
    fs::write(&out_path, rust).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display());
    });

    eprintln!(
        "aether_enclave: compiled {} ({} bytes) → {}",
        wat_path.file_name().unwrap().to_string_lossy(),
        wasm.len(),
        out_path.strip_prefix(&manifest_dir).unwrap_or(&out_path).display()
    );
}

fn generate_rust(wasm: &[u8]) -> String {
    let mut out = String::from(
        "//! AUTO-GENERATED by build.rs from `payload.wat` — do not edit manually.\n\
         //! Rebuild with `cargo build` after changing the payload.\n\n\
         /// Raw WebAssembly module bytes embedded in the unikernel image.\n\
         pub const WASM_BYTES: &[u8] = &[\n",
    );

    for (i, byte) in wasm.iter().enumerate() {
        if i % 12 == 0 {
            out.push_str("    ");
        }
        out.push_str(&format!("0x{byte:02X}, "));
        if (i + 1) % 12 == 0 {
            out.push('\n');
        }
    }
    if !wasm.is_empty() && wasm.len() % 12 != 0 {
        out.push('\n');
    }
    out.push_str("];\n");
    out
}
