[build]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.x86_64-unknown-none]
runner = "bootimage runner"
rustflags = [
    "-C", "relocation-model=static",
]