//! Builds `aerospace_payload` for `wasm32-unknown-unknown` and embeds the `.wasm` in the kernel.
//!
//! Nested WASM builds use an isolated `target/wasm-payload` directory to avoid cargo#8938
//! `.cargo-lock` deadlocks with the parent kernel build.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .expect("enclave_kernel must live inside the workspace root");
    let payload_dir = workspace_root.join("aerospace_payload");
    let out_path = manifest_dir.join("src").join("wasm_payload.rs");
    let wasm_target_dir = workspace_root.join("target").join("wasm-payload");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../aerospace_payload/src");
    println!("cargo:rerun-if-changed={}", payload_dir.join("Cargo.toml").display());
    println!("cargo:rerun-if-changed={}", payload_dir.join("src").display());

    let status = Command::new(env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .current_dir(&workspace_root)
        .env("CARGO_TARGET_DIR", &wasm_target_dir)
        // Shield the WASM compiler from inheriting physical hardware linker flags
        .env_remove("RUSTFLAGS")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .args([
            "build",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
            "-p",
            "aerospace_payload",
        ])
        .status()
        .expect("Failed to execute WASM build");

    assert!(status.success(), "WASM Payload failed to compile!");

    let wasm_path = wasm_target_dir
        .join("wasm32-unknown-unknown")
        .join("release")
        .join("aerospace_payload.wasm");

    let wasm = fs::read(&wasm_path).unwrap_or_else(|e| {
        panic!(
            "failed to read WASM artifact at {}: {e}",
            wasm_path.display()
        );
    });

    fs::write(&out_path, generate_rust(&wasm)).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display());
    });

    eprintln!(
        "enclave_kernel: embedded aerospace_payload ({} bytes) → {}",
        wasm.len(),
        out_path
            .strip_prefix(&manifest_dir)
            .unwrap_or(&out_path)
            .display()
    );
}

fn generate_rust(wasm: &[u8]) -> String {
    let mut out = String::from(
        "//! AUTO-GENERATED by enclave_kernel/build.rs — do not edit manually.\n\
         //! Source: `aerospace_payload` (wasm32-unknown-unknown release).\n\
         //! Stored in flash (`.rodata`); does not consume SRAM.\n\n\
         /// Raw WebAssembly module bytes embedded in the unikernel image.\n\
         pub const WASM_BYTES: &[u8] = &[\n",
    );

    for (i, byte) in wasm.iter().enumerate() {
        if i % 12 == 0 {
            out.push_str("    ");
        }
        out.push_str(&format!("0x{byte:02X}, "));
        if (i + 1) % 12 == 0 {
            out.push('\n');
        }
    }
    if !wasm.is_empty() && wasm.len() % 12 != 0 {
        out.push('\n');
    }
    out.push_str("];\n");
    out
}