//! Builds `aerospace_payload` (strict + relaxed) and embeds both `.wasm` blobs in flash.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .expect("enclave_kernel must live inside the workspace root");
    let payload_dir = workspace_root.join("aerospace_payload");
    let out_path = manifest_dir.join("src").join("wasm_payload.rs");
    let wasm_target_dir = workspace_root.join("target").join("wasm-payload");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../aerospace_payload/src");
    println!("cargo:rerun-if-changed={}", payload_dir.join("Cargo.toml").display());
    println!("cargo:rerun-if-changed={}", payload_dir.join("src").display());

    let strict = build_payload(&workspace_root, &wasm_target_dir, &[]);
    let relaxed = build_payload(&workspace_root, &wasm_target_dir, &["--features", "relaxed"]);

    fs::write(
        &out_path,
        generate_rust(&strict, &relaxed),
    )
    .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));

    eprintln!(
        "enclave_kernel: embedded WASM strict={} relaxed={} bytes → {}",
        strict.len(),
        relaxed.len(),
        out_path
            .strip_prefix(&manifest_dir)
            .unwrap_or(&out_path)
            .display()
    );
}

fn build_payload(workspace_root: &std::path::Path, wasm_target_dir: &PathBuf, extra: &[&str]) -> Vec<u8> {
    let mut args = vec![
        "build",
        "--target",
        "wasm32-unknown-unknown",
        "--release",
        "-p",
        "aerospace_payload",
    ];
    args.extend_from_slice(extra);

    let status = Command::new(env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .current_dir(workspace_root)
        .env("CARGO_TARGET_DIR", wasm_target_dir)
        .env_remove("RUSTFLAGS")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .args(&args)
        .status()
        .expect("Failed to execute WASM build");

    assert!(status.success(), "WASM Payload failed to compile!");

    let wasm_path = wasm_target_dir
        .join("wasm32-unknown-unknown")
        .join("release")
        .join("aerospace_payload.wasm");

    fs::read(&wasm_path).unwrap_or_else(|e| {
        panic!(
            "failed to read WASM artifact at {}: {e}",
            wasm_path.display()
        )
    })
}

fn generate_rust(strict: &[u8], relaxed: &[u8]) -> String {
    let mut out = String::from(
        "//! AUTO-GENERATED by enclave_kernel/build.rs — do not edit manually.\n\
         //! Source: `aerospace_payload` strict + relaxed (wasm32-unknown-unknown release).\n\
         //! Stored in flash (`.rodata`); does not consume SRAM.\n\n",
    );
    out.push_str("/// Strict mission WASM (default limits from host profile).\n");
    out.push_str("pub const WASM_STRICT: &[u8] = &");
    out.push_str(&byte_array(strict));
    out.push_str(";\n\n/// Relaxed mission WASM (same imports; demo / high-tolerance slot).\n");
    out.push_str("pub const WASM_RELAXED: &[u8] = &");
    out.push_str(&byte_array(relaxed));
    out.push_str(
        r";



/// Select embedded payload: slot 0 = strict, 1 = relaxed.
pub fn wasm_bytes_for_slot(slot: u8) -> &'static [u8] {
    match slot {
        1 => WASM_RELAXED,
        _ => WASM_STRICT,
    }
}
",
    );
    out
}

fn byte_array(bytes: &[u8]) -> String {
    let mut out = String::from("[\n");
    for (i, byte) in bytes.iter().enumerate() {
        if i % 12 == 0 {
            out.push_str("    ");
        }
        out.push_str(&format!("0x{byte:02X}, "));
        if (i + 1) % 12 == 0 {
            out.push('\n');
        }
    }
    if !bytes.is_empty() && bytes.len() % 12 != 0 {
        out.push('\n');
    }
    out.push(']');
    out
}
