//! Builds `aerospace_payload` for `wasm32-unknown-unknown` and embeds the `.wasm` in the kernel.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .expect("enclave_kernel must live inside the workspace root");
    let payload_dir = workspace_root.join("aerospace_payload");
    let out_path = manifest_dir.join("src").join("wasm_payload.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", payload_dir.join("Cargo.toml").display());
    println!("cargo:rerun-if-changed={}", payload_dir.join("src").display());

    let status = Command::new(env::var("CARGO").unwrap_or_else(|_| "cargo".into()))
        .current_dir(workspace_root)
        .args([
            "build",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
            "-p",
            "aerospace_payload",
        ])
        .status()
        .expect("failed to spawn `cargo` for aerospace_payload");

    if !status.success() {
        panic!("aerospace_payload build failed with status {status}");
    }

    let target_dir = env::var("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| workspace_root.join("target"));

    let wasm_path = target_dir
        .join("wasm32-unknown-unknown")
        .join("release")
        .join("aerospace_payload.wasm");

    let wasm = fs::read(&wasm_path).unwrap_or_else(|e| {
        panic!(
            "failed to read WASM artifact at {}: {e}",
            wasm_path.display()
        );
    });

    fs::write(&out_path, generate_rust(&wasm)).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display());
    });

    eprintln!(
        "enclave_kernel: embedded aerospace_payload ({} bytes) → {}",
        wasm.len(),
        out_path.strip_prefix(&manifest_dir).unwrap_or(&out_path).display()
    );
}

fn generate_rust(wasm: &[u8]) -> String {
    let mut out = String::from(
        "//! AUTO-GENERATED by enclave_kernel/build.rs — do not edit manually.\n\
         //! Source: `aerospace_payload` (wasm32-unknown-unknown release).\n\n\
         /// Raw WebAssembly module bytes embedded in the unikernel image.\n\
         pub const WASM_BYTES: &[u8] = &[\n",
    );

    for (i, byte) in wasm.iter().enumerate() {
        if i % 12 == 0 {
            out.push_str("    ");
        }
        out.push_str(&format!("0x{byte:02X}, "));
        if (i + 1) % 12 == 0 {
            out.push('\n');
        }
    }
    if !wasm.is_empty() && wasm.len() % 12 != 0 {
        out.push('\n');
    }
    out.push_str("];\n");
    out
}
